### PR TITLE
Separately handle WEBUI_TAG

### PR DESCRIPTION
**Pull request by tiraboschi**

### CODE REVIEW

**Comment by tiraboschi** [comment]
@mareklibra can you please review?
Required by: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/161
Fixes: https://github.com/kubevirt/hyperconverged-cluster-operator/issues/160

**Review by mareklibra — APPROVED** [review]

**Comment by tiraboschi** [comment]
@mareklibra can you please also create a new tagged release that contains this one?

**Comment by mareklibra** [comment]
@tiraboschi , sure, np.

Is this fix intended for 2.0.0?
If so, please backport to the `web-ui-v2.0.0` branch. Or let me know - I can do it.

Please note, this operator will not be present in 2.1.

**Comment by tiraboschi** [comment]
No, 2.1 only.
I know that we are not going to have it on 2.1 but currently we have it on master and master is broken due to this.

**Comment by mareklibra** [comment]
done: https://github.com/kubevirt/web-ui-operator/releases/tag/v0.1.12

**Pull request merged**
